hydra:
  # Default multi-run activated
  mode: MULTIRUN
  sweeper:
    params:
      data.graph_types: reply, retweet, mention, late_fuse
      model.encoder: gnn, gat, gatv2, gine, sage, transformer, nnconv

  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

data:
  data_dir: ../GraphAnalysis/resources/217a03a0498411f180769c29764a0d18
  graph_types: late_fuse
  split: [0.70, 0.15, 0.15]

model:
  encoder: gine
  decoder: mlp
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 1e-5
  hidden_dim: 128
  embed_dim: 64
  dropout: 0.2
  neg_ratio: 1.0
  decoder_hidden: 64
  decoder_dropout: 0.3
  scheduler: false
  grad_clip: 0.0
  early_stopping_patience: 10
  seed: 777
  fusion: mean
  batch_size: 512
  num_neighbors: [10, 5]

evaluation:
  neg_ratios: [1, 9, 100]

output:
  output_dir: output/models
  log_dir: output/logs
  mlflow_tracking_uri: sqlite:///mlflow.db
